name: Update daily challenge

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Set up .env from secrets
        run: |
          printf "EBIRD_API_KEY=%s\n" "${EBIRD_API_KEY}" > .env
        env:
          EBIRD_API_KEY: ${{ secrets.EBIRD_API_KEY }}


      - name: Run daily script to find birds in every subregion available
        run: |
          for file in ./scripts/data/regions/*-subregions.json; do
            filename=$(basename "$file" -subregions.json)
            output="./public/data/daily-subregion-birds.json"
            python ./scripts/generate-daily-region-data.py "$file" "$output"
          done

      - name: Run daily challenge script to generate the bird(s) of the day
        run: |
          current_date=$(date -u +%F)
          python ./scripts/generate-daily-birds.py --days 60 --date "$current_date" --subregions public/data/daily-subregion-birds.json

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update challenge: ${timestamp}" || exit 0
          git push
